import * as LucideIcons from "lucide-react";

export type IconName = keyof typeof AVAILABLE_ICONS;

export const AVAILABLE_ICONS = {
   Activity: LucideIcons.Activity,
   Apple: LucideIcons.Apple,
   Archive: LucideIcons.Archive,
   Banknote: LucideIcons.Banknote,
   Bike: LucideIcons.Bike,
   BookOpen: LucideIcons.BookOpen,
   Briefcase: LucideIcons.Briefcase,
   Bus: LucideIcons.Bus,
   Calendar: LucideIcons.Calendar,
   Camera: LucideIcons.Camera,
   Car: LucideIcons.Car,
   Clock: LucideIcons.Clock,
   Coffee: LucideIcons.Coffee,
   Coins: LucideIcons.Coins,
   CreditCard: LucideIcons.CreditCard,
   DollarSign: LucideIcons.DollarSign,
   Droplet: LucideIcons.Droplet,
   Dumbbell: LucideIcons.Dumbbell,
   FileText: LucideIcons.FileText,
   Film: LucideIcons.Film,
   FolderOpen: LucideIcons.FolderOpen,
   Fuel: LucideIcons.Fuel,
   Gamepad: LucideIcons.Gamepad,
   Gift: LucideIcons.Gift,
   Globe: LucideIcons.Globe,
   GraduationCap: LucideIcons.GraduationCap,
   Heart: LucideIcons.Heart,
   Home: LucideIcons.Home,
   IceCream: LucideIcons.IceCream,
   Laptop: LucideIcons.Laptop,
   Lightbulb: LucideIcons.Lightbulb,
   Mail: LucideIcons.Mail,
   MapPin: LucideIcons.MapPin,
   MessageSquare: LucideIcons.MessageSquare,
   Music: LucideIcons.Music,
   Package: LucideIcons.Package,
   Paintbrush: LucideIcons.Paintbrush,
   Pencil: LucideIcons.Pencil,
   Phone: LucideIcons.Phone,
   PiggyBank: LucideIcons.PiggyBank,
   Pill: LucideIcons.Pill,
   Pizza: LucideIcons.Pizza,
   Plane: LucideIcons.Plane,
   Scissors: LucideIcons.Scissors,
   Settings: LucideIcons.Settings,
   Shirt: LucideIcons.Shirt,
   ShoppingBag: LucideIcons.ShoppingBag,
   ShoppingCart: LucideIcons.ShoppingCart,
   Star: LucideIcons.Star,
   Stethoscope: LucideIcons.Stethoscope,
   Store: LucideIcons.Store,
   Tag: LucideIcons.Tag,
   Train: LucideIcons.Train,
   TrendingDown: LucideIcons.TrendingDown,
   TrendingUp: LucideIcons.TrendingUp,
   Tv: LucideIcons.Tv,
   User: LucideIcons.User,
   Users: LucideIcons.Users,
   UtensilsCrossed: LucideIcons.UtensilsCrossed,
   Wallet: LucideIcons.Wallet,
   Wifi: LucideIcons.Wifi,
   Wine: LucideIcons.Wine,
   Wrench: LucideIcons.Wrench,
   Zap: LucideIcons.Zap,
};

export const getIconComponent = (iconName: IconName) => {
   return AVAILABLE_ICONS[iconName];
};

export const ICON_NAMES = Object.keys(AVAILABLE_ICONS) as IconName[];

export const ICON_CATEGORIES = {
   Education: ["BookOpen", "GraduationCap", "Pencil"],
   Entertainment: ["Film", "Gamepad", "Music", "Star"],
   Finance: [
      "Banknote",
      "Coins",
      "CreditCard",
      "DollarSign",
      "PiggyBank",
      "TrendingDown",
      "TrendingUp",
      "Wallet",
   ],
   Food: ["Coffee", "IceCream", "Pizza", "UtensilsCrossed", "Wine", "Apple"],
   Health: ["Heart", "Pill", "Stethoscope", "Dumbbell", "Activity"],
   Home: ["Home", "Lightbulb", "Settings", "Wrench"],
   Other: [
      "Archive",
      "Droplet",
      "FolderOpen",
      "Globe",
      "MapPin",
      "Paintbrush",
      "Scissors",
      "Shirt",
   ],
   People: ["User", "Users", "MessageSquare"],
   Shopping: ["ShoppingBag", "ShoppingCart", "Store", "Tag", "Gift", "Package"],
   Technology: ["Laptop", "Phone", "Wifi", "Camera", "Tv", "Zap"],
   Transport: ["Bike", "Bus", "Car", "Fuel", "Plane", "Train"],
   Work: ["Briefcase", "Calendar", "Clock", "FileText", "Mail"],
} as const;

export type IconCategory = keyof typeof ICON_CATEGORIES;
