export type {
   ArrayCondition,
   ArrayOperator,
   BooleanCondition,
   BooleanOperator,
   Condition,
   ConditionGroup,
   CustomCondition,
   DateCondition,
   DateOperator,
   EvaluationResult,
   GroupEvaluationResult,
   LogicalOperator,
   NumberCondition,
   NumberOperator,
   StringCondition,
   StringOperator,
} from "@f-o-t/condition-evaluator";
export {
   ConditionGroup as ConditionGroupSchema,
   isConditionGroup,
} from "@f-o-t/condition-evaluator";
export {
   analyzeConsequenceUsage,
   analyzeFieldUsage,
   analyzeOperatorUsage,
   analyzeRuleComplexity,
   analyzeRuleSet,
   type ConsequenceUsage,
   type FieldUsage,
   findLeastUsedFields,
   findMostComplexRules,
   formatRuleSetAnalysis,
   type OperatorUsage,
   type RuleComplexity,
   type RuleSetAnalysis,
} from "./analyzer/analysis";
export {
   all,
   and,
   any,
   arr,
   bool,
   type ConditionBuilder,
   type ConditionBuilderState,
   conditions,
   date,
   num,
   or,
   resetBuilderIds,
   str,
} from "./builder/conditions";
export {
   createRule,
   type RuleBuilder,
   type RuleBuilderState,
   rule,
} from "./builder/rule";
export {
   type Cache,
   type CacheEntry,
   type CacheOptions,
   createCache,
} from "./cache/cache";
export { createNoopCache } from "./cache/noop";
export {
   type EvaluateRuleOptions,
   type EvaluateRulesOptions,
   type EvaluateRulesResult,
   evaluateRule,
   evaluateRules,
} from "./core/evaluate";
export {
   filterByCategory,
   filterByEnabled,
   filterByIds,
   filterByTags,
   filterRules,
} from "./core/filter";
export {
   type GroupByField,
   type GroupedRules,
   groupByCategory,
   groupByCustom,
   groupByEnabled,
   groupByPriority,
   groupRules,
} from "./core/group";
export {
   type SortDirection,
   type SortField,
   type SortOptions,
   sortByCreatedAt,
   sortByName,
   sortByPriority,
   sortByUpdatedAt,
   sortRules,
} from "./core/sort";
export { createEngine, type Engine } from "./engine/engine";
export {
   addRule,
   addRuleSet,
   addRules,
   clearRules,
   cloneState,
   disableRule,
   enableRule,
   getRule,
   getRuleSet,
   getRuleSets,
   getRules,
   getRulesInSet,
   removeRule,
   removeRuleSet,
   updateRule,
} from "./engine/state";
export {
   analyzeOptimizations,
   buildIndex,
   type CategoryIndex,
   type FieldIndex,
   filterRulesForContext,
   getIndexStats,
   getRuleById,
   getRulesByCategory,
   getRulesByField,
   getRulesByFields,
   getRulesByPriority,
   getRulesByPriorityRange,
   getRulesByTag,
   getRulesByTags,
   type IndexOptions,
   type OptimizationSuggestion,
   type PriorityIndex,
   type RuleIndex,
   type TagIndex,
} from "./optimizer/index-builder";
export {
   cloneRule,
   deserializeRule,
   deserializeRuleSet,
   diffRuleSets,
   type ExportFormat,
   exportRules,
   exportToJson,
   type ImportOptions,
   type ImportResult,
   importFromJson,
   importRules,
   mergeRuleSets,
   type OrphanedReference,
   type SerializedRule,
   type SerializedRuleSet,
   serializeRule,
   serializeRuleSet,
} from "./serialization/serializer";
export {
   type BatchSimulationResult,
   batchSimulate,
   findRulesAffectedByContextChange,
   formatSimulationResult,
   type SimulationContext,
   type SimulationResult,
   simulate,
   simulateSingleRule,
   type WhatIfResult,
   whatIf,
} from "./simulation/simulator";
export type {
   CacheConfig,
   EngineConfig,
   EngineHooks,
   Logger,
   LogLevel,
   ResolvedEngineConfig,
   ValidationConfig,
   VersioningConfig,
} from "./types/config";
export {
   CacheConfigSchema,
   getDefaultCacheConfig,
   getDefaultConflictResolution,
   getDefaultLogLevel,
   getDefaultValidationConfig,
   getDefaultVersioningConfig,
   LogLevelSchema,
   parseCacheConfig,
   parseValidationConfig,
   parseVersioningConfig,
   ValidationConfigSchema,
   VersioningConfigSchema,
} from "./types/config";
export type {
   AggregatedConsequence,
   Consequence,
   ConsequenceDefinitions,
   ConsequenceInput,
   DefaultConsequences,
   InferConsequencePayload,
   InferConsequenceType,
} from "./types/consequence";
export type {
   ConflictResolutionStrategy,
   EngineExecutionResult,
   EvaluateConfig,
   EvaluateOptions,
   EvaluationContext,
   RuleEvaluationResult,
} from "./types/evaluation";
export {
   ConflictResolutionStrategySchema,
   EvaluateConfigSchema,
   EvaluateOptionsSchema,
} from "./types/evaluation";
export type {
   Rule,
   RuleFilters,
   RuleInput,
   RuleSchemaType,
   RuleSet,
   RuleSetInput,
   RuleSetSchemaType,
} from "./types/rule";
export { RuleSchema, RuleSetSchema } from "./types/rule";
export type {
   CacheStats,
   EngineState,
   EngineStats,
   OptimizerState,
   RuleStats,
} from "./types/state";
export {
   CacheStatsSchema,
   createInitialOptimizerState,
   createInitialRuleStats,
   createInitialState,
   EngineStatsSchema,
   RuleStatsSchema,
} from "./types/state";
export { hashContext, hashRules } from "./utils/hash";
export { generateId } from "./utils/id";
export {
   measureTime,
   measureTimeAsync,
   type TimingResult,
   withTimeout,
} from "./utils/time";
export {
   type Conflict,
   type ConflictDetectionOptions,
   type ConflictType,
   detectConflicts,
   formatConflicts,
   getConflictsBySeverity,
   getConflictsByType,
   hasConflicts,
   hasErrors,
} from "./validation/conflicts";
export {
   checkIntegrity,
   checkRuleFieldCoverage,
   formatIntegrityResult,
   getUsedFields,
   getUsedOperators,
   type IntegrityCheckOptions,
   type IntegrityCheckResult,
   type IntegrityIssue,
} from "./validation/integrity";
export {
   createRuleValidator,
   parseRule,
   type ResolvedValidationOptions,
   safeParseRule,
   type ValidationError,
   ValidationErrorSchema,
   type ValidationOptions,
   ValidationOptionsSchema,
   type ValidationResult,
   ValidationResultSchema,
   validateConditions,
   validateRule,
   validateRuleSet,
   validateRules,
} from "./validation/schema";
export {
   addVersion,
   compareVersions,
   createVersionStore,
   formatVersionHistory,
   getAllVersions,
   getHistory,
   getLatestVersion,
   getVersion,
   getVersionsByChangeType,
   getVersionsByDateRange,
   pruneOldVersions,
   type RuleVersion,
   rollbackToVersion,
   type VersionHistory,
   type VersionStore,
} from "./versioning/version-store";
