import {
   AlertCircle,
   Award,
   Baby,
   BookOpen,
   Briefcase,
   Building,
   Car,
   Coffee,
   CreditCard,
   Dumbbell,
   Fuel,
   Gift,
   Heart,
   Home,
   Landmark,
   type LucideIcon,
   Megaphone,
   Music,
   Package,
   Paperclip,
   PiggyBank,
   Plane,
   Receipt,
   Scale,
   ShoppingCart,
   Smartphone,
   TrendingDown,
   TrendingUp,
   UserMinus,
   Users,
   Utensils,
   Wallet,
   Wifi,
   Zap,
} from "lucide-react";

export type CategoryIconOption = {
   value: string;
   label: string;
   icon: LucideIcon;
};

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
   "alert-circle": AlertCircle,
   award: Award,
   baby: Baby,
   "book-open": BookOpen,
   briefcase: Briefcase,
   building: Building,
   car: Car,
   coffee: Coffee,
   "credit-card": CreditCard,
   dumbbell: Dumbbell,
   fuel: Fuel,
   gift: Gift,
   heart: Heart,
   home: Home,
   landmark: Landmark,
   megaphone: Megaphone,
   music: Music,
   package: Package,
   paperclip: Paperclip,
   "piggy-bank": PiggyBank,
   plane: Plane,
   receipt: Receipt,
   scale: Scale,
   "shopping-cart": ShoppingCart,
   smartphone: Smartphone,
   "trending-down": TrendingDown,
   "trending-up": TrendingUp,
   "user-minus": UserMinus,
   users: Users,
   utensils: Utensils,
   wallet: Wallet,
   wifi: Wifi,
   zap: Zap,
};

export const CATEGORY_ICON_OPTIONS: CategoryIconOption[] = [
   { value: "briefcase", label: "Negócios", icon: Briefcase },
   { value: "wallet", label: "Carteira", icon: Wallet },
   { value: "credit-card", label: "Cartão", icon: CreditCard },
   { value: "shopping-cart", label: "Compras", icon: ShoppingCart },
   { value: "package", label: "Produtos", icon: Package },
   { value: "receipt", label: "Recibos", icon: Receipt },
   { value: "landmark", label: "Banco", icon: Landmark },
   { value: "home", label: "Casa", icon: Home },
   { value: "car", label: "Veículo", icon: Car },
   { value: "fuel", label: "Combustível", icon: Fuel },
   { value: "utensils", label: "Alimentação", icon: Utensils },
   { value: "plane", label: "Viagem", icon: Plane },
   { value: "heart", label: "Saúde", icon: Heart },
   { value: "book-open", label: "Educação", icon: BookOpen },
   { value: "smartphone", label: "Tecnologia", icon: Smartphone },
   { value: "megaphone", label: "Marketing", icon: Megaphone },
   { value: "users", label: "Equipe", icon: Users },
   { value: "gift", label: "Benefícios", icon: Gift },
   { value: "zap", label: "Energia", icon: Zap },
   { value: "scale", label: "Fiscal", icon: Scale },
];
