/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShareTargetRouteImport } from './routes/share-target'
import { Route as PwaRedirectRouteImport } from './routes/pwa-redirect'
import { Route as FileHandlerRouteImport } from './routes/file-handler'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthMagicLinkRouteImport } from './routes/auth/magic-link'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthEmailVerificationRouteImport } from './routes/auth/email-verification'
import { Route as AuthAnonymousRouteImport } from './routes/auth/anonymous'
import { Route as SlugOnboardingRouteImport } from './routes/$slug/onboarding'
import { Route as SlugImportRouteImport } from './routes/$slug/import'
import { Route as SlugExportRouteImport } from './routes/$slug/export'
import { Route as SlugDashboardRouteImport } from './routes/$slug/_dashboard'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthSignInEmailRouteImport } from './routes/auth/sign-in/email'
import { Route as SlugDashboardSettingsRouteImport } from './routes/$slug/_dashboard/settings'
import { Route as SlugDashboardSearchRouteImport } from './routes/$slug/_dashboard/search'
import { Route as SlugDashboardProfileRouteImport } from './routes/$slug/_dashboard/profile'
import { Route as SlugDashboardPlansRouteImport } from './routes/$slug/_dashboard/plans'
import { Route as SlugDashboardOrganizationRouteImport } from './routes/$slug/_dashboard/organization'
import { Route as SlugDashboardManagePlanRouteImport } from './routes/$slug/_dashboard/manage-plan'
import { Route as SlugDashboardHomeRouteImport } from './routes/$slug/_dashboard/home'
import { Route as SlugDashboardTransactionsIndexRouteImport } from './routes/$slug/_dashboard/transactions.index'
import { Route as SlugDashboardTagsIndexRouteImport } from './routes/$slug/_dashboard/tags/index'
import { Route as SlugDashboardSettingsIndexRouteImport } from './routes/$slug/_dashboard/settings/index'
import { Route as SlugDashboardOrganizationIndexRouteImport } from './routes/$slug/_dashboard/organization/index'
import { Route as SlugDashboardInterestTemplatesIndexRouteImport } from './routes/$slug/_dashboard/interest-templates/index'
import { Route as SlugDashboardInsightsIndexRouteImport } from './routes/$slug/_dashboard/insights.index'
import { Route as SlugDashboardGoalsIndexRouteImport } from './routes/$slug/_dashboard/goals/index'
import { Route as SlugDashboardDashboardsIndexRouteImport } from './routes/$slug/_dashboard/dashboards.index'
import { Route as SlugDashboardCounterpartiesIndexRouteImport } from './routes/$slug/_dashboard/counterparties/index'
import { Route as SlugDashboardCostCentersIndexRouteImport } from './routes/$slug/_dashboard/cost-centers/index'
import { Route as SlugDashboardCategoriesIndexRouteImport } from './routes/$slug/_dashboard/categories/index'
import { Route as SlugDashboardBudgetsIndexRouteImport } from './routes/$slug/_dashboard/budgets/index'
import { Route as SlugDashboardBillsIndexRouteImport } from './routes/$slug/_dashboard/bills/index'
import { Route as SlugDashboardBankAccountsIndexRouteImport } from './routes/$slug/_dashboard/bank-accounts.index'
import { Route as SlugDashboardAutomationsIndexRouteImport } from './routes/$slug/_dashboard/automations/index'
import { Route as CallbackOrganizationInvitationInvitationIdRouteImport } from './routes/callback/organization/invitation.$invitationId'
import { Route as SlugDashboardTransactionsTransactionIdRouteImport } from './routes/$slug/_dashboard/transactions.$transactionId'
import { Route as SlugDashboardTagsTagIdRouteImport } from './routes/$slug/_dashboard/tags/$tagId'
import { Route as SlugDashboardSettingsSecurityRouteImport } from './routes/$slug/_dashboard/settings/security'
import { Route as SlugDashboardSettingsProfileRouteImport } from './routes/$slug/_dashboard/settings/profile'
import { Route as SlugDashboardSettingsPreferencesRouteImport } from './routes/$slug/_dashboard/settings/preferences'
import { Route as SlugDashboardSettingsNotificationsRouteImport } from './routes/$slug/_dashboard/settings/notifications'
import { Route as SlugDashboardSettingsBillingRouteImport } from './routes/$slug/_dashboard/settings/billing'
import { Route as SlugDashboardOrganizationTeamsRouteImport } from './routes/$slug/_dashboard/organization/teams'
import { Route as SlugDashboardOrganizationMembersRouteImport } from './routes/$slug/_dashboard/organization/members'
import { Route as SlugDashboardOrganizationInvitesRouteImport } from './routes/$slug/_dashboard/organization/invites'
import { Route as SlugDashboardInterestTemplatesInterestTemplateIdRouteImport } from './routes/$slug/_dashboard/interest-templates/$interestTemplateId'
import { Route as SlugDashboardInsightsInsightIdRouteImport } from './routes/$slug/_dashboard/insights.$insightId'
import { Route as SlugDashboardDashboardsDashboardIdRouteImport } from './routes/$slug/_dashboard/dashboards.$dashboardId'
import { Route as SlugDashboardCounterpartiesCounterpartyIdRouteImport } from './routes/$slug/_dashboard/counterparties/$counterpartyId'
import { Route as SlugDashboardCostCentersCostCenterIdRouteImport } from './routes/$slug/_dashboard/cost-centers/$costCenterId'
import { Route as SlugDashboardCategoriesCategoryIdRouteImport } from './routes/$slug/_dashboard/categories/$categoryId'
import { Route as SlugDashboardBudgetsBudgetIdRouteImport } from './routes/$slug/_dashboard/budgets/$budgetId'
import { Route as SlugDashboardBillsBillIdRouteImport } from './routes/$slug/_dashboard/bills.$billId'
import { Route as SlugDashboardBankAccountsBankAccountIdRouteImport } from './routes/$slug/_dashboard/bank-accounts.$bankAccountId'
import { Route as SlugDashboardAutomationsAutomationIdRouteImport } from './routes/$slug/_dashboard/automations/$automationId'
import { Route as SlugDashboardOrganizationTeamsTeamIdRouteImport } from './routes/$slug/_dashboard/organization/teams/$teamId'

const ShareTargetRoute = ShareTargetRouteImport.update({
  id: '/share-target',
  path: '/share-target',
  getParentRoute: () => rootRouteImport,
} as any)
const PwaRedirectRoute = PwaRedirectRouteImport.update({
  id: '/pwa-redirect',
  path: '/pwa-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const FileHandlerRoute = FileHandlerRouteImport.update({
  id: '/file-handler',
  path: '/file-handler',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmailVerificationRoute = AuthEmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAnonymousRoute = AuthAnonymousRouteImport.update({
  id: '/anonymous',
  path: '/anonymous',
  getParentRoute: () => AuthRoute,
} as any)
const SlugOnboardingRoute = SlugOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SlugRoute,
} as any)
const SlugImportRoute = SlugImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => SlugRoute,
} as any)
const SlugExportRoute = SlugExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDashboardRoute = SlugDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => SlugRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSignInRoute,
} as any)
const AuthSignInEmailRoute = AuthSignInEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthSignInRoute,
} as any)
const SlugDashboardSettingsRoute = SlugDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardSearchRoute = SlugDashboardSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardProfileRoute = SlugDashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardPlansRoute = SlugDashboardPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardOrganizationRoute =
  SlugDashboardOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardManagePlanRoute = SlugDashboardManagePlanRouteImport.update({
  id: '/manage-plan',
  path: '/manage-plan',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardHomeRoute = SlugDashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardTransactionsIndexRoute =
  SlugDashboardTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardTagsIndexRoute = SlugDashboardTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardSettingsIndexRoute =
  SlugDashboardSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardOrganizationIndexRoute =
  SlugDashboardOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SlugDashboardOrganizationRoute,
  } as any)
const SlugDashboardInterestTemplatesIndexRoute =
  SlugDashboardInterestTemplatesIndexRouteImport.update({
    id: '/interest-templates/',
    path: '/interest-templates/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardInsightsIndexRoute =
  SlugDashboardInsightsIndexRouteImport.update({
    id: '/insights/',
    path: '/insights/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardGoalsIndexRoute = SlugDashboardGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardDashboardsIndexRoute =
  SlugDashboardDashboardsIndexRouteImport.update({
    id: '/dashboards/',
    path: '/dashboards/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCounterpartiesIndexRoute =
  SlugDashboardCounterpartiesIndexRouteImport.update({
    id: '/counterparties/',
    path: '/counterparties/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCostCentersIndexRoute =
  SlugDashboardCostCentersIndexRouteImport.update({
    id: '/cost-centers/',
    path: '/cost-centers/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCategoriesIndexRoute =
  SlugDashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBudgetsIndexRoute =
  SlugDashboardBudgetsIndexRouteImport.update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBillsIndexRoute = SlugDashboardBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardBankAccountsIndexRoute =
  SlugDashboardBankAccountsIndexRouteImport.update({
    id: '/bank-accounts/',
    path: '/bank-accounts/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardAutomationsIndexRoute =
  SlugDashboardAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const CallbackOrganizationInvitationInvitationIdRoute =
  CallbackOrganizationInvitationInvitationIdRouteImport.update({
    id: '/callback/organization/invitation/$invitationId',
    path: '/callback/organization/invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SlugDashboardTransactionsTransactionIdRoute =
  SlugDashboardTransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardTagsTagIdRoute = SlugDashboardTagsTagIdRouteImport.update({
  id: '/tags/$tagId',
  path: '/tags/$tagId',
  getParentRoute: () => SlugDashboardRoute,
} as any)
const SlugDashboardSettingsSecurityRoute =
  SlugDashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsProfileRoute =
  SlugDashboardSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsPreferencesRoute =
  SlugDashboardSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsNotificationsRoute =
  SlugDashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardSettingsBillingRoute =
  SlugDashboardSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => SlugDashboardSettingsRoute,
  } as any)
const SlugDashboardOrganizationTeamsRoute =
  SlugDashboardOrganizationTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => SlugDashboardOrganizationRoute,
  } as any)
const SlugDashboardOrganizationMembersRoute =
  SlugDashboardOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => SlugDashboardOrganizationRoute,
  } as any)
const SlugDashboardOrganizationInvitesRoute =
  SlugDashboardOrganizationInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => SlugDashboardOrganizationRoute,
  } as any)
const SlugDashboardInterestTemplatesInterestTemplateIdRoute =
  SlugDashboardInterestTemplatesInterestTemplateIdRouteImport.update({
    id: '/interest-templates/$interestTemplateId',
    path: '/interest-templates/$interestTemplateId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardInsightsInsightIdRoute =
  SlugDashboardInsightsInsightIdRouteImport.update({
    id: '/insights/$insightId',
    path: '/insights/$insightId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardDashboardsDashboardIdRoute =
  SlugDashboardDashboardsDashboardIdRouteImport.update({
    id: '/dashboards/$dashboardId',
    path: '/dashboards/$dashboardId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCounterpartiesCounterpartyIdRoute =
  SlugDashboardCounterpartiesCounterpartyIdRouteImport.update({
    id: '/counterparties/$counterpartyId',
    path: '/counterparties/$counterpartyId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCostCentersCostCenterIdRoute =
  SlugDashboardCostCentersCostCenterIdRouteImport.update({
    id: '/cost-centers/$costCenterId',
    path: '/cost-centers/$costCenterId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardCategoriesCategoryIdRoute =
  SlugDashboardCategoriesCategoryIdRouteImport.update({
    id: '/categories/$categoryId',
    path: '/categories/$categoryId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBudgetsBudgetIdRoute =
  SlugDashboardBudgetsBudgetIdRouteImport.update({
    id: '/budgets/$budgetId',
    path: '/budgets/$budgetId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBillsBillIdRoute =
  SlugDashboardBillsBillIdRouteImport.update({
    id: '/bills/$billId',
    path: '/bills/$billId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardBankAccountsBankAccountIdRoute =
  SlugDashboardBankAccountsBankAccountIdRouteImport.update({
    id: '/bank-accounts/$bankAccountId',
    path: '/bank-accounts/$bankAccountId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardAutomationsAutomationIdRoute =
  SlugDashboardAutomationsAutomationIdRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => SlugDashboardRoute,
  } as any)
const SlugDashboardOrganizationTeamsTeamIdRoute =
  SlugDashboardOrganizationTeamsTeamIdRouteImport.update({
    id: '/$teamId',
    path: '/$teamId',
    getParentRoute: () => SlugDashboardOrganizationTeamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof SlugDashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/file-handler': typeof FileHandlerRoute
  '/pwa-redirect': typeof PwaRedirectRoute
  '/share-target': typeof ShareTargetRoute
  '/$slug/export': typeof SlugExportRoute
  '/$slug/import': typeof SlugImportRoute
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$slug/home': typeof SlugDashboardHomeRoute
  '/$slug/manage-plan': typeof SlugDashboardManagePlanRoute
  '/$slug/organization': typeof SlugDashboardOrganizationRouteWithChildren
  '/$slug/plans': typeof SlugDashboardPlansRoute
  '/$slug/profile': typeof SlugDashboardProfileRoute
  '/$slug/search': typeof SlugDashboardSearchRoute
  '/$slug/settings': typeof SlugDashboardSettingsRouteWithChildren
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/$slug/automations/$automationId': typeof SlugDashboardAutomationsAutomationIdRoute
  '/$slug/bank-accounts/$bankAccountId': typeof SlugDashboardBankAccountsBankAccountIdRoute
  '/$slug/bills/$billId': typeof SlugDashboardBillsBillIdRoute
  '/$slug/budgets/$budgetId': typeof SlugDashboardBudgetsBudgetIdRoute
  '/$slug/categories/$categoryId': typeof SlugDashboardCategoriesCategoryIdRoute
  '/$slug/cost-centers/$costCenterId': typeof SlugDashboardCostCentersCostCenterIdRoute
  '/$slug/counterparties/$counterpartyId': typeof SlugDashboardCounterpartiesCounterpartyIdRoute
  '/$slug/dashboards/$dashboardId': typeof SlugDashboardDashboardsDashboardIdRoute
  '/$slug/insights/$insightId': typeof SlugDashboardInsightsInsightIdRoute
  '/$slug/interest-templates/$interestTemplateId': typeof SlugDashboardInterestTemplatesInterestTemplateIdRoute
  '/$slug/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/organization/teams': typeof SlugDashboardOrganizationTeamsRouteWithChildren
  '/$slug/settings/billing': typeof SlugDashboardSettingsBillingRoute
  '/$slug/settings/notifications': typeof SlugDashboardSettingsNotificationsRoute
  '/$slug/settings/preferences': typeof SlugDashboardSettingsPreferencesRoute
  '/$slug/settings/profile': typeof SlugDashboardSettingsProfileRoute
  '/$slug/settings/security': typeof SlugDashboardSettingsSecurityRoute
  '/$slug/tags/$tagId': typeof SlugDashboardTagsTagIdRoute
  '/$slug/transactions/$transactionId': typeof SlugDashboardTransactionsTransactionIdRoute
  '/callback/organization/invitation/$invitationId': typeof CallbackOrganizationInvitationInvitationIdRoute
  '/$slug/automations': typeof SlugDashboardAutomationsIndexRoute
  '/$slug/bank-accounts': typeof SlugDashboardBankAccountsIndexRoute
  '/$slug/bills': typeof SlugDashboardBillsIndexRoute
  '/$slug/budgets': typeof SlugDashboardBudgetsIndexRoute
  '/$slug/categories': typeof SlugDashboardCategoriesIndexRoute
  '/$slug/cost-centers': typeof SlugDashboardCostCentersIndexRoute
  '/$slug/counterparties': typeof SlugDashboardCounterpartiesIndexRoute
  '/$slug/dashboards': typeof SlugDashboardDashboardsIndexRoute
  '/$slug/goals': typeof SlugDashboardGoalsIndexRoute
  '/$slug/insights': typeof SlugDashboardInsightsIndexRoute
  '/$slug/interest-templates': typeof SlugDashboardInterestTemplatesIndexRoute
  '/$slug/organization/': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/settings/': typeof SlugDashboardSettingsIndexRoute
  '/$slug/tags': typeof SlugDashboardTagsIndexRoute
  '/$slug/transactions': typeof SlugDashboardTransactionsIndexRoute
  '/$slug/organization/teams/$teamId': typeof SlugDashboardOrganizationTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof SlugDashboardRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/file-handler': typeof FileHandlerRoute
  '/pwa-redirect': typeof PwaRedirectRoute
  '/share-target': typeof ShareTargetRoute
  '/$slug/export': typeof SlugExportRoute
  '/$slug/import': typeof SlugImportRoute
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$slug/home': typeof SlugDashboardHomeRoute
  '/$slug/manage-plan': typeof SlugDashboardManagePlanRoute
  '/$slug/plans': typeof SlugDashboardPlansRoute
  '/$slug/profile': typeof SlugDashboardProfileRoute
  '/$slug/search': typeof SlugDashboardSearchRoute
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/$slug/automations/$automationId': typeof SlugDashboardAutomationsAutomationIdRoute
  '/$slug/bank-accounts/$bankAccountId': typeof SlugDashboardBankAccountsBankAccountIdRoute
  '/$slug/bills/$billId': typeof SlugDashboardBillsBillIdRoute
  '/$slug/budgets/$budgetId': typeof SlugDashboardBudgetsBudgetIdRoute
  '/$slug/categories/$categoryId': typeof SlugDashboardCategoriesCategoryIdRoute
  '/$slug/cost-centers/$costCenterId': typeof SlugDashboardCostCentersCostCenterIdRoute
  '/$slug/counterparties/$counterpartyId': typeof SlugDashboardCounterpartiesCounterpartyIdRoute
  '/$slug/dashboards/$dashboardId': typeof SlugDashboardDashboardsDashboardIdRoute
  '/$slug/insights/$insightId': typeof SlugDashboardInsightsInsightIdRoute
  '/$slug/interest-templates/$interestTemplateId': typeof SlugDashboardInterestTemplatesInterestTemplateIdRoute
  '/$slug/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/organization/teams': typeof SlugDashboardOrganizationTeamsRouteWithChildren
  '/$slug/settings/billing': typeof SlugDashboardSettingsBillingRoute
  '/$slug/settings/notifications': typeof SlugDashboardSettingsNotificationsRoute
  '/$slug/settings/preferences': typeof SlugDashboardSettingsPreferencesRoute
  '/$slug/settings/profile': typeof SlugDashboardSettingsProfileRoute
  '/$slug/settings/security': typeof SlugDashboardSettingsSecurityRoute
  '/$slug/tags/$tagId': typeof SlugDashboardTagsTagIdRoute
  '/$slug/transactions/$transactionId': typeof SlugDashboardTransactionsTransactionIdRoute
  '/callback/organization/invitation/$invitationId': typeof CallbackOrganizationInvitationInvitationIdRoute
  '/$slug/automations': typeof SlugDashboardAutomationsIndexRoute
  '/$slug/bank-accounts': typeof SlugDashboardBankAccountsIndexRoute
  '/$slug/bills': typeof SlugDashboardBillsIndexRoute
  '/$slug/budgets': typeof SlugDashboardBudgetsIndexRoute
  '/$slug/categories': typeof SlugDashboardCategoriesIndexRoute
  '/$slug/cost-centers': typeof SlugDashboardCostCentersIndexRoute
  '/$slug/counterparties': typeof SlugDashboardCounterpartiesIndexRoute
  '/$slug/dashboards': typeof SlugDashboardDashboardsIndexRoute
  '/$slug/goals': typeof SlugDashboardGoalsIndexRoute
  '/$slug/insights': typeof SlugDashboardInsightsIndexRoute
  '/$slug/interest-templates': typeof SlugDashboardInterestTemplatesIndexRoute
  '/$slug/organization': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/settings': typeof SlugDashboardSettingsIndexRoute
  '/$slug/tags': typeof SlugDashboardTagsIndexRoute
  '/$slug/transactions': typeof SlugDashboardTransactionsIndexRoute
  '/$slug/organization/teams/$teamId': typeof SlugDashboardOrganizationTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$slug': typeof SlugRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/file-handler': typeof FileHandlerRoute
  '/pwa-redirect': typeof PwaRedirectRoute
  '/share-target': typeof ShareTargetRoute
  '/$slug/_dashboard': typeof SlugDashboardRouteWithChildren
  '/$slug/export': typeof SlugExportRoute
  '/$slug/import': typeof SlugImportRoute
  '/$slug/onboarding': typeof SlugOnboardingRoute
  '/auth/anonymous': typeof AuthAnonymousRoute
  '/auth/email-verification': typeof AuthEmailVerificationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/sign-in': typeof AuthSignInRouteWithChildren
  '/auth/sign-up': typeof AuthSignUpRoute
  '/$slug/_dashboard/home': typeof SlugDashboardHomeRoute
  '/$slug/_dashboard/manage-plan': typeof SlugDashboardManagePlanRoute
  '/$slug/_dashboard/organization': typeof SlugDashboardOrganizationRouteWithChildren
  '/$slug/_dashboard/plans': typeof SlugDashboardPlansRoute
  '/$slug/_dashboard/profile': typeof SlugDashboardProfileRoute
  '/$slug/_dashboard/search': typeof SlugDashboardSearchRoute
  '/$slug/_dashboard/settings': typeof SlugDashboardSettingsRouteWithChildren
  '/auth/sign-in/email': typeof AuthSignInEmailRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/$slug/_dashboard/automations/$automationId': typeof SlugDashboardAutomationsAutomationIdRoute
  '/$slug/_dashboard/bank-accounts/$bankAccountId': typeof SlugDashboardBankAccountsBankAccountIdRoute
  '/$slug/_dashboard/bills/$billId': typeof SlugDashboardBillsBillIdRoute
  '/$slug/_dashboard/budgets/$budgetId': typeof SlugDashboardBudgetsBudgetIdRoute
  '/$slug/_dashboard/categories/$categoryId': typeof SlugDashboardCategoriesCategoryIdRoute
  '/$slug/_dashboard/cost-centers/$costCenterId': typeof SlugDashboardCostCentersCostCenterIdRoute
  '/$slug/_dashboard/counterparties/$counterpartyId': typeof SlugDashboardCounterpartiesCounterpartyIdRoute
  '/$slug/_dashboard/dashboards/$dashboardId': typeof SlugDashboardDashboardsDashboardIdRoute
  '/$slug/_dashboard/insights/$insightId': typeof SlugDashboardInsightsInsightIdRoute
  '/$slug/_dashboard/interest-templates/$interestTemplateId': typeof SlugDashboardInterestTemplatesInterestTemplateIdRoute
  '/$slug/_dashboard/organization/invites': typeof SlugDashboardOrganizationInvitesRoute
  '/$slug/_dashboard/organization/members': typeof SlugDashboardOrganizationMembersRoute
  '/$slug/_dashboard/organization/teams': typeof SlugDashboardOrganizationTeamsRouteWithChildren
  '/$slug/_dashboard/settings/billing': typeof SlugDashboardSettingsBillingRoute
  '/$slug/_dashboard/settings/notifications': typeof SlugDashboardSettingsNotificationsRoute
  '/$slug/_dashboard/settings/preferences': typeof SlugDashboardSettingsPreferencesRoute
  '/$slug/_dashboard/settings/profile': typeof SlugDashboardSettingsProfileRoute
  '/$slug/_dashboard/settings/security': typeof SlugDashboardSettingsSecurityRoute
  '/$slug/_dashboard/tags/$tagId': typeof SlugDashboardTagsTagIdRoute
  '/$slug/_dashboard/transactions/$transactionId': typeof SlugDashboardTransactionsTransactionIdRoute
  '/callback/organization/invitation/$invitationId': typeof CallbackOrganizationInvitationInvitationIdRoute
  '/$slug/_dashboard/automations/': typeof SlugDashboardAutomationsIndexRoute
  '/$slug/_dashboard/bank-accounts/': typeof SlugDashboardBankAccountsIndexRoute
  '/$slug/_dashboard/bills/': typeof SlugDashboardBillsIndexRoute
  '/$slug/_dashboard/budgets/': typeof SlugDashboardBudgetsIndexRoute
  '/$slug/_dashboard/categories/': typeof SlugDashboardCategoriesIndexRoute
  '/$slug/_dashboard/cost-centers/': typeof SlugDashboardCostCentersIndexRoute
  '/$slug/_dashboard/counterparties/': typeof SlugDashboardCounterpartiesIndexRoute
  '/$slug/_dashboard/dashboards/': typeof SlugDashboardDashboardsIndexRoute
  '/$slug/_dashboard/goals/': typeof SlugDashboardGoalsIndexRoute
  '/$slug/_dashboard/insights/': typeof SlugDashboardInsightsIndexRoute
  '/$slug/_dashboard/interest-templates/': typeof SlugDashboardInterestTemplatesIndexRoute
  '/$slug/_dashboard/organization/': typeof SlugDashboardOrganizationIndexRoute
  '/$slug/_dashboard/settings/': typeof SlugDashboardSettingsIndexRoute
  '/$slug/_dashboard/tags/': typeof SlugDashboardTagsIndexRoute
  '/$slug/_dashboard/transactions/': typeof SlugDashboardTransactionsIndexRoute
  '/$slug/_dashboard/organization/teams/$teamId': typeof SlugDashboardOrganizationTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/auth'
    | '/file-handler'
    | '/pwa-redirect'
    | '/share-target'
    | '/$slug/export'
    | '/$slug/import'
    | '/$slug/onboarding'
    | '/auth/anonymous'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$slug/home'
    | '/$slug/manage-plan'
    | '/$slug/organization'
    | '/$slug/plans'
    | '/$slug/profile'
    | '/$slug/search'
    | '/$slug/settings'
    | '/auth/sign-in/email'
    | '/auth/sign-in/'
    | '/$slug/automations/$automationId'
    | '/$slug/bank-accounts/$bankAccountId'
    | '/$slug/bills/$billId'
    | '/$slug/budgets/$budgetId'
    | '/$slug/categories/$categoryId'
    | '/$slug/cost-centers/$costCenterId'
    | '/$slug/counterparties/$counterpartyId'
    | '/$slug/dashboards/$dashboardId'
    | '/$slug/insights/$insightId'
    | '/$slug/interest-templates/$interestTemplateId'
    | '/$slug/organization/invites'
    | '/$slug/organization/members'
    | '/$slug/organization/teams'
    | '/$slug/settings/billing'
    | '/$slug/settings/notifications'
    | '/$slug/settings/preferences'
    | '/$slug/settings/profile'
    | '/$slug/settings/security'
    | '/$slug/tags/$tagId'
    | '/$slug/transactions/$transactionId'
    | '/callback/organization/invitation/$invitationId'
    | '/$slug/automations'
    | '/$slug/bank-accounts'
    | '/$slug/bills'
    | '/$slug/budgets'
    | '/$slug/categories'
    | '/$slug/cost-centers'
    | '/$slug/counterparties'
    | '/$slug/dashboards'
    | '/$slug/goals'
    | '/$slug/insights'
    | '/$slug/interest-templates'
    | '/$slug/organization/'
    | '/$slug/settings/'
    | '/$slug/tags'
    | '/$slug/transactions'
    | '/$slug/organization/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/auth'
    | '/file-handler'
    | '/pwa-redirect'
    | '/share-target'
    | '/$slug/export'
    | '/$slug/import'
    | '/$slug/onboarding'
    | '/auth/anonymous'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-up'
    | '/$slug/home'
    | '/$slug/manage-plan'
    | '/$slug/plans'
    | '/$slug/profile'
    | '/$slug/search'
    | '/auth/sign-in/email'
    | '/auth/sign-in'
    | '/$slug/automations/$automationId'
    | '/$slug/bank-accounts/$bankAccountId'
    | '/$slug/bills/$billId'
    | '/$slug/budgets/$budgetId'
    | '/$slug/categories/$categoryId'
    | '/$slug/cost-centers/$costCenterId'
    | '/$slug/counterparties/$counterpartyId'
    | '/$slug/dashboards/$dashboardId'
    | '/$slug/insights/$insightId'
    | '/$slug/interest-templates/$interestTemplateId'
    | '/$slug/organization/invites'
    | '/$slug/organization/members'
    | '/$slug/organization/teams'
    | '/$slug/settings/billing'
    | '/$slug/settings/notifications'
    | '/$slug/settings/preferences'
    | '/$slug/settings/profile'
    | '/$slug/settings/security'
    | '/$slug/tags/$tagId'
    | '/$slug/transactions/$transactionId'
    | '/callback/organization/invitation/$invitationId'
    | '/$slug/automations'
    | '/$slug/bank-accounts'
    | '/$slug/bills'
    | '/$slug/budgets'
    | '/$slug/categories'
    | '/$slug/cost-centers'
    | '/$slug/counterparties'
    | '/$slug/dashboards'
    | '/$slug/goals'
    | '/$slug/insights'
    | '/$slug/interest-templates'
    | '/$slug/organization'
    | '/$slug/settings'
    | '/$slug/tags'
    | '/$slug/transactions'
    | '/$slug/organization/teams/$teamId'
  id:
    | '__root__'
    | '/$slug'
    | '/auth'
    | '/file-handler'
    | '/pwa-redirect'
    | '/share-target'
    | '/$slug/_dashboard'
    | '/$slug/export'
    | '/$slug/import'
    | '/$slug/onboarding'
    | '/auth/anonymous'
    | '/auth/email-verification'
    | '/auth/forgot-password'
    | '/auth/magic-link'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$slug/_dashboard/home'
    | '/$slug/_dashboard/manage-plan'
    | '/$slug/_dashboard/organization'
    | '/$slug/_dashboard/plans'
    | '/$slug/_dashboard/profile'
    | '/$slug/_dashboard/search'
    | '/$slug/_dashboard/settings'
    | '/auth/sign-in/email'
    | '/auth/sign-in/'
    | '/$slug/_dashboard/automations/$automationId'
    | '/$slug/_dashboard/bank-accounts/$bankAccountId'
    | '/$slug/_dashboard/bills/$billId'
    | '/$slug/_dashboard/budgets/$budgetId'
    | '/$slug/_dashboard/categories/$categoryId'
    | '/$slug/_dashboard/cost-centers/$costCenterId'
    | '/$slug/_dashboard/counterparties/$counterpartyId'
    | '/$slug/_dashboard/dashboards/$dashboardId'
    | '/$slug/_dashboard/insights/$insightId'
    | '/$slug/_dashboard/interest-templates/$interestTemplateId'
    | '/$slug/_dashboard/organization/invites'
    | '/$slug/_dashboard/organization/members'
    | '/$slug/_dashboard/organization/teams'
    | '/$slug/_dashboard/settings/billing'
    | '/$slug/_dashboard/settings/notifications'
    | '/$slug/_dashboard/settings/preferences'
    | '/$slug/_dashboard/settings/profile'
    | '/$slug/_dashboard/settings/security'
    | '/$slug/_dashboard/tags/$tagId'
    | '/$slug/_dashboard/transactions/$transactionId'
    | '/callback/organization/invitation/$invitationId'
    | '/$slug/_dashboard/automations/'
    | '/$slug/_dashboard/bank-accounts/'
    | '/$slug/_dashboard/bills/'
    | '/$slug/_dashboard/budgets/'
    | '/$slug/_dashboard/categories/'
    | '/$slug/_dashboard/cost-centers/'
    | '/$slug/_dashboard/counterparties/'
    | '/$slug/_dashboard/dashboards/'
    | '/$slug/_dashboard/goals/'
    | '/$slug/_dashboard/insights/'
    | '/$slug/_dashboard/interest-templates/'
    | '/$slug/_dashboard/organization/'
    | '/$slug/_dashboard/settings/'
    | '/$slug/_dashboard/tags/'
    | '/$slug/_dashboard/transactions/'
    | '/$slug/_dashboard/organization/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SlugRoute: typeof SlugRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  FileHandlerRoute: typeof FileHandlerRoute
  PwaRedirectRoute: typeof PwaRedirectRoute
  ShareTargetRoute: typeof ShareTargetRoute
  CallbackOrganizationInvitationInvitationIdRoute: typeof CallbackOrganizationInvitationInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/share-target': {
      id: '/share-target'
      path: '/share-target'
      fullPath: '/share-target'
      preLoaderRoute: typeof ShareTargetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pwa-redirect': {
      id: '/pwa-redirect'
      path: '/pwa-redirect'
      fullPath: '/pwa-redirect'
      preLoaderRoute: typeof PwaRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-handler': {
      id: '/file-handler'
      path: '/file-handler'
      fullPath: '/file-handler'
      preLoaderRoute: typeof FileHandlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/email-verification': {
      id: '/auth/email-verification'
      path: '/email-verification'
      fullPath: '/auth/email-verification'
      preLoaderRoute: typeof AuthEmailVerificationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/anonymous': {
      id: '/auth/anonymous'
      path: '/anonymous'
      fullPath: '/auth/anonymous'
      preLoaderRoute: typeof AuthAnonymousRouteImport
      parentRoute: typeof AuthRoute
    }
    '/$slug/onboarding': {
      id: '/$slug/onboarding'
      path: '/onboarding'
      fullPath: '/$slug/onboarding'
      preLoaderRoute: typeof SlugOnboardingRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/import': {
      id: '/$slug/import'
      path: '/import'
      fullPath: '/$slug/import'
      preLoaderRoute: typeof SlugImportRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/export': {
      id: '/$slug/export'
      path: '/export'
      fullPath: '/$slug/export'
      preLoaderRoute: typeof SlugExportRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/_dashboard': {
      id: '/$slug/_dashboard'
      path: ''
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugDashboardRouteImport
      parentRoute: typeof SlugRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthSignInRoute
    }
    '/auth/sign-in/email': {
      id: '/auth/sign-in/email'
      path: '/email'
      fullPath: '/auth/sign-in/email'
      preLoaderRoute: typeof AuthSignInEmailRouteImport
      parentRoute: typeof AuthSignInRoute
    }
    '/$slug/_dashboard/settings': {
      id: '/$slug/_dashboard/settings'
      path: '/settings'
      fullPath: '/$slug/settings'
      preLoaderRoute: typeof SlugDashboardSettingsRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/search': {
      id: '/$slug/_dashboard/search'
      path: '/search'
      fullPath: '/$slug/search'
      preLoaderRoute: typeof SlugDashboardSearchRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/profile': {
      id: '/$slug/_dashboard/profile'
      path: '/profile'
      fullPath: '/$slug/profile'
      preLoaderRoute: typeof SlugDashboardProfileRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/plans': {
      id: '/$slug/_dashboard/plans'
      path: '/plans'
      fullPath: '/$slug/plans'
      preLoaderRoute: typeof SlugDashboardPlansRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/organization': {
      id: '/$slug/_dashboard/organization'
      path: '/organization'
      fullPath: '/$slug/organization'
      preLoaderRoute: typeof SlugDashboardOrganizationRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/manage-plan': {
      id: '/$slug/_dashboard/manage-plan'
      path: '/manage-plan'
      fullPath: '/$slug/manage-plan'
      preLoaderRoute: typeof SlugDashboardManagePlanRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/home': {
      id: '/$slug/_dashboard/home'
      path: '/home'
      fullPath: '/$slug/home'
      preLoaderRoute: typeof SlugDashboardHomeRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/transactions/': {
      id: '/$slug/_dashboard/transactions/'
      path: '/transactions'
      fullPath: '/$slug/transactions'
      preLoaderRoute: typeof SlugDashboardTransactionsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/tags/': {
      id: '/$slug/_dashboard/tags/'
      path: '/tags'
      fullPath: '/$slug/tags'
      preLoaderRoute: typeof SlugDashboardTagsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/settings/': {
      id: '/$slug/_dashboard/settings/'
      path: '/'
      fullPath: '/$slug/settings/'
      preLoaderRoute: typeof SlugDashboardSettingsIndexRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/organization/': {
      id: '/$slug/_dashboard/organization/'
      path: '/'
      fullPath: '/$slug/organization/'
      preLoaderRoute: typeof SlugDashboardOrganizationIndexRouteImport
      parentRoute: typeof SlugDashboardOrganizationRoute
    }
    '/$slug/_dashboard/interest-templates/': {
      id: '/$slug/_dashboard/interest-templates/'
      path: '/interest-templates'
      fullPath: '/$slug/interest-templates'
      preLoaderRoute: typeof SlugDashboardInterestTemplatesIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/insights/': {
      id: '/$slug/_dashboard/insights/'
      path: '/insights'
      fullPath: '/$slug/insights'
      preLoaderRoute: typeof SlugDashboardInsightsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/goals/': {
      id: '/$slug/_dashboard/goals/'
      path: '/goals'
      fullPath: '/$slug/goals'
      preLoaderRoute: typeof SlugDashboardGoalsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/dashboards/': {
      id: '/$slug/_dashboard/dashboards/'
      path: '/dashboards'
      fullPath: '/$slug/dashboards'
      preLoaderRoute: typeof SlugDashboardDashboardsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/counterparties/': {
      id: '/$slug/_dashboard/counterparties/'
      path: '/counterparties'
      fullPath: '/$slug/counterparties'
      preLoaderRoute: typeof SlugDashboardCounterpartiesIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/cost-centers/': {
      id: '/$slug/_dashboard/cost-centers/'
      path: '/cost-centers'
      fullPath: '/$slug/cost-centers'
      preLoaderRoute: typeof SlugDashboardCostCentersIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/categories/': {
      id: '/$slug/_dashboard/categories/'
      path: '/categories'
      fullPath: '/$slug/categories'
      preLoaderRoute: typeof SlugDashboardCategoriesIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/budgets/': {
      id: '/$slug/_dashboard/budgets/'
      path: '/budgets'
      fullPath: '/$slug/budgets'
      preLoaderRoute: typeof SlugDashboardBudgetsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/bills/': {
      id: '/$slug/_dashboard/bills/'
      path: '/bills'
      fullPath: '/$slug/bills'
      preLoaderRoute: typeof SlugDashboardBillsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/bank-accounts/': {
      id: '/$slug/_dashboard/bank-accounts/'
      path: '/bank-accounts'
      fullPath: '/$slug/bank-accounts'
      preLoaderRoute: typeof SlugDashboardBankAccountsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/automations/': {
      id: '/$slug/_dashboard/automations/'
      path: '/automations'
      fullPath: '/$slug/automations'
      preLoaderRoute: typeof SlugDashboardAutomationsIndexRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/callback/organization/invitation/$invitationId': {
      id: '/callback/organization/invitation/$invitationId'
      path: '/callback/organization/invitation/$invitationId'
      fullPath: '/callback/organization/invitation/$invitationId'
      preLoaderRoute: typeof CallbackOrganizationInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/_dashboard/transactions/$transactionId': {
      id: '/$slug/_dashboard/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/$slug/transactions/$transactionId'
      preLoaderRoute: typeof SlugDashboardTransactionsTransactionIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/tags/$tagId': {
      id: '/$slug/_dashboard/tags/$tagId'
      path: '/tags/$tagId'
      fullPath: '/$slug/tags/$tagId'
      preLoaderRoute: typeof SlugDashboardTagsTagIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/settings/security': {
      id: '/$slug/_dashboard/settings/security'
      path: '/security'
      fullPath: '/$slug/settings/security'
      preLoaderRoute: typeof SlugDashboardSettingsSecurityRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/profile': {
      id: '/$slug/_dashboard/settings/profile'
      path: '/profile'
      fullPath: '/$slug/settings/profile'
      preLoaderRoute: typeof SlugDashboardSettingsProfileRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/preferences': {
      id: '/$slug/_dashboard/settings/preferences'
      path: '/preferences'
      fullPath: '/$slug/settings/preferences'
      preLoaderRoute: typeof SlugDashboardSettingsPreferencesRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/notifications': {
      id: '/$slug/_dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/$slug/settings/notifications'
      preLoaderRoute: typeof SlugDashboardSettingsNotificationsRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/settings/billing': {
      id: '/$slug/_dashboard/settings/billing'
      path: '/billing'
      fullPath: '/$slug/settings/billing'
      preLoaderRoute: typeof SlugDashboardSettingsBillingRouteImport
      parentRoute: typeof SlugDashboardSettingsRoute
    }
    '/$slug/_dashboard/organization/teams': {
      id: '/$slug/_dashboard/organization/teams'
      path: '/teams'
      fullPath: '/$slug/organization/teams'
      preLoaderRoute: typeof SlugDashboardOrganizationTeamsRouteImport
      parentRoute: typeof SlugDashboardOrganizationRoute
    }
    '/$slug/_dashboard/organization/members': {
      id: '/$slug/_dashboard/organization/members'
      path: '/members'
      fullPath: '/$slug/organization/members'
      preLoaderRoute: typeof SlugDashboardOrganizationMembersRouteImport
      parentRoute: typeof SlugDashboardOrganizationRoute
    }
    '/$slug/_dashboard/organization/invites': {
      id: '/$slug/_dashboard/organization/invites'
      path: '/invites'
      fullPath: '/$slug/organization/invites'
      preLoaderRoute: typeof SlugDashboardOrganizationInvitesRouteImport
      parentRoute: typeof SlugDashboardOrganizationRoute
    }
    '/$slug/_dashboard/interest-templates/$interestTemplateId': {
      id: '/$slug/_dashboard/interest-templates/$interestTemplateId'
      path: '/interest-templates/$interestTemplateId'
      fullPath: '/$slug/interest-templates/$interestTemplateId'
      preLoaderRoute: typeof SlugDashboardInterestTemplatesInterestTemplateIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/insights/$insightId': {
      id: '/$slug/_dashboard/insights/$insightId'
      path: '/insights/$insightId'
      fullPath: '/$slug/insights/$insightId'
      preLoaderRoute: typeof SlugDashboardInsightsInsightIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/dashboards/$dashboardId': {
      id: '/$slug/_dashboard/dashboards/$dashboardId'
      path: '/dashboards/$dashboardId'
      fullPath: '/$slug/dashboards/$dashboardId'
      preLoaderRoute: typeof SlugDashboardDashboardsDashboardIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/counterparties/$counterpartyId': {
      id: '/$slug/_dashboard/counterparties/$counterpartyId'
      path: '/counterparties/$counterpartyId'
      fullPath: '/$slug/counterparties/$counterpartyId'
      preLoaderRoute: typeof SlugDashboardCounterpartiesCounterpartyIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/cost-centers/$costCenterId': {
      id: '/$slug/_dashboard/cost-centers/$costCenterId'
      path: '/cost-centers/$costCenterId'
      fullPath: '/$slug/cost-centers/$costCenterId'
      preLoaderRoute: typeof SlugDashboardCostCentersCostCenterIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/categories/$categoryId': {
      id: '/$slug/_dashboard/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/$slug/categories/$categoryId'
      preLoaderRoute: typeof SlugDashboardCategoriesCategoryIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/budgets/$budgetId': {
      id: '/$slug/_dashboard/budgets/$budgetId'
      path: '/budgets/$budgetId'
      fullPath: '/$slug/budgets/$budgetId'
      preLoaderRoute: typeof SlugDashboardBudgetsBudgetIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/bills/$billId': {
      id: '/$slug/_dashboard/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/$slug/bills/$billId'
      preLoaderRoute: typeof SlugDashboardBillsBillIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/bank-accounts/$bankAccountId': {
      id: '/$slug/_dashboard/bank-accounts/$bankAccountId'
      path: '/bank-accounts/$bankAccountId'
      fullPath: '/$slug/bank-accounts/$bankAccountId'
      preLoaderRoute: typeof SlugDashboardBankAccountsBankAccountIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/automations/$automationId': {
      id: '/$slug/_dashboard/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/$slug/automations/$automationId'
      preLoaderRoute: typeof SlugDashboardAutomationsAutomationIdRouteImport
      parentRoute: typeof SlugDashboardRoute
    }
    '/$slug/_dashboard/organization/teams/$teamId': {
      id: '/$slug/_dashboard/organization/teams/$teamId'
      path: '/$teamId'
      fullPath: '/$slug/organization/teams/$teamId'
      preLoaderRoute: typeof SlugDashboardOrganizationTeamsTeamIdRouteImport
      parentRoute: typeof SlugDashboardOrganizationTeamsRoute
    }
  }
}

interface SlugDashboardOrganizationTeamsRouteChildren {
  SlugDashboardOrganizationTeamsTeamIdRoute: typeof SlugDashboardOrganizationTeamsTeamIdRoute
}

const SlugDashboardOrganizationTeamsRouteChildren: SlugDashboardOrganizationTeamsRouteChildren =
  {
    SlugDashboardOrganizationTeamsTeamIdRoute:
      SlugDashboardOrganizationTeamsTeamIdRoute,
  }

const SlugDashboardOrganizationTeamsRouteWithChildren =
  SlugDashboardOrganizationTeamsRoute._addFileChildren(
    SlugDashboardOrganizationTeamsRouteChildren,
  )

interface SlugDashboardOrganizationRouteChildren {
  SlugDashboardOrganizationInvitesRoute: typeof SlugDashboardOrganizationInvitesRoute
  SlugDashboardOrganizationMembersRoute: typeof SlugDashboardOrganizationMembersRoute
  SlugDashboardOrganizationTeamsRoute: typeof SlugDashboardOrganizationTeamsRouteWithChildren
  SlugDashboardOrganizationIndexRoute: typeof SlugDashboardOrganizationIndexRoute
}

const SlugDashboardOrganizationRouteChildren: SlugDashboardOrganizationRouteChildren =
  {
    SlugDashboardOrganizationInvitesRoute:
      SlugDashboardOrganizationInvitesRoute,
    SlugDashboardOrganizationMembersRoute:
      SlugDashboardOrganizationMembersRoute,
    SlugDashboardOrganizationTeamsRoute:
      SlugDashboardOrganizationTeamsRouteWithChildren,
    SlugDashboardOrganizationIndexRoute: SlugDashboardOrganizationIndexRoute,
  }

const SlugDashboardOrganizationRouteWithChildren =
  SlugDashboardOrganizationRoute._addFileChildren(
    SlugDashboardOrganizationRouteChildren,
  )

interface SlugDashboardSettingsRouteChildren {
  SlugDashboardSettingsBillingRoute: typeof SlugDashboardSettingsBillingRoute
  SlugDashboardSettingsNotificationsRoute: typeof SlugDashboardSettingsNotificationsRoute
  SlugDashboardSettingsPreferencesRoute: typeof SlugDashboardSettingsPreferencesRoute
  SlugDashboardSettingsProfileRoute: typeof SlugDashboardSettingsProfileRoute
  SlugDashboardSettingsSecurityRoute: typeof SlugDashboardSettingsSecurityRoute
  SlugDashboardSettingsIndexRoute: typeof SlugDashboardSettingsIndexRoute
}

const SlugDashboardSettingsRouteChildren: SlugDashboardSettingsRouteChildren = {
  SlugDashboardSettingsBillingRoute: SlugDashboardSettingsBillingRoute,
  SlugDashboardSettingsNotificationsRoute:
    SlugDashboardSettingsNotificationsRoute,
  SlugDashboardSettingsPreferencesRoute: SlugDashboardSettingsPreferencesRoute,
  SlugDashboardSettingsProfileRoute: SlugDashboardSettingsProfileRoute,
  SlugDashboardSettingsSecurityRoute: SlugDashboardSettingsSecurityRoute,
  SlugDashboardSettingsIndexRoute: SlugDashboardSettingsIndexRoute,
}

const SlugDashboardSettingsRouteWithChildren =
  SlugDashboardSettingsRoute._addFileChildren(
    SlugDashboardSettingsRouteChildren,
  )

interface SlugDashboardRouteChildren {
  SlugDashboardHomeRoute: typeof SlugDashboardHomeRoute
  SlugDashboardManagePlanRoute: typeof SlugDashboardManagePlanRoute
  SlugDashboardOrganizationRoute: typeof SlugDashboardOrganizationRouteWithChildren
  SlugDashboardPlansRoute: typeof SlugDashboardPlansRoute
  SlugDashboardProfileRoute: typeof SlugDashboardProfileRoute
  SlugDashboardSearchRoute: typeof SlugDashboardSearchRoute
  SlugDashboardSettingsRoute: typeof SlugDashboardSettingsRouteWithChildren
  SlugDashboardAutomationsAutomationIdRoute: typeof SlugDashboardAutomationsAutomationIdRoute
  SlugDashboardBankAccountsBankAccountIdRoute: typeof SlugDashboardBankAccountsBankAccountIdRoute
  SlugDashboardBillsBillIdRoute: typeof SlugDashboardBillsBillIdRoute
  SlugDashboardBudgetsBudgetIdRoute: typeof SlugDashboardBudgetsBudgetIdRoute
  SlugDashboardCategoriesCategoryIdRoute: typeof SlugDashboardCategoriesCategoryIdRoute
  SlugDashboardCostCentersCostCenterIdRoute: typeof SlugDashboardCostCentersCostCenterIdRoute
  SlugDashboardCounterpartiesCounterpartyIdRoute: typeof SlugDashboardCounterpartiesCounterpartyIdRoute
  SlugDashboardDashboardsDashboardIdRoute: typeof SlugDashboardDashboardsDashboardIdRoute
  SlugDashboardInsightsInsightIdRoute: typeof SlugDashboardInsightsInsightIdRoute
  SlugDashboardInterestTemplatesInterestTemplateIdRoute: typeof SlugDashboardInterestTemplatesInterestTemplateIdRoute
  SlugDashboardTagsTagIdRoute: typeof SlugDashboardTagsTagIdRoute
  SlugDashboardTransactionsTransactionIdRoute: typeof SlugDashboardTransactionsTransactionIdRoute
  SlugDashboardAutomationsIndexRoute: typeof SlugDashboardAutomationsIndexRoute
  SlugDashboardBankAccountsIndexRoute: typeof SlugDashboardBankAccountsIndexRoute
  SlugDashboardBillsIndexRoute: typeof SlugDashboardBillsIndexRoute
  SlugDashboardBudgetsIndexRoute: typeof SlugDashboardBudgetsIndexRoute
  SlugDashboardCategoriesIndexRoute: typeof SlugDashboardCategoriesIndexRoute
  SlugDashboardCostCentersIndexRoute: typeof SlugDashboardCostCentersIndexRoute
  SlugDashboardCounterpartiesIndexRoute: typeof SlugDashboardCounterpartiesIndexRoute
  SlugDashboardDashboardsIndexRoute: typeof SlugDashboardDashboardsIndexRoute
  SlugDashboardGoalsIndexRoute: typeof SlugDashboardGoalsIndexRoute
  SlugDashboardInsightsIndexRoute: typeof SlugDashboardInsightsIndexRoute
  SlugDashboardInterestTemplatesIndexRoute: typeof SlugDashboardInterestTemplatesIndexRoute
  SlugDashboardTagsIndexRoute: typeof SlugDashboardTagsIndexRoute
  SlugDashboardTransactionsIndexRoute: typeof SlugDashboardTransactionsIndexRoute
}

const SlugDashboardRouteChildren: SlugDashboardRouteChildren = {
  SlugDashboardHomeRoute: SlugDashboardHomeRoute,
  SlugDashboardManagePlanRoute: SlugDashboardManagePlanRoute,
  SlugDashboardOrganizationRoute: SlugDashboardOrganizationRouteWithChildren,
  SlugDashboardPlansRoute: SlugDashboardPlansRoute,
  SlugDashboardProfileRoute: SlugDashboardProfileRoute,
  SlugDashboardSearchRoute: SlugDashboardSearchRoute,
  SlugDashboardSettingsRoute: SlugDashboardSettingsRouteWithChildren,
  SlugDashboardAutomationsAutomationIdRoute:
    SlugDashboardAutomationsAutomationIdRoute,
  SlugDashboardBankAccountsBankAccountIdRoute:
    SlugDashboardBankAccountsBankAccountIdRoute,
  SlugDashboardBillsBillIdRoute: SlugDashboardBillsBillIdRoute,
  SlugDashboardBudgetsBudgetIdRoute: SlugDashboardBudgetsBudgetIdRoute,
  SlugDashboardCategoriesCategoryIdRoute:
    SlugDashboardCategoriesCategoryIdRoute,
  SlugDashboardCostCentersCostCenterIdRoute:
    SlugDashboardCostCentersCostCenterIdRoute,
  SlugDashboardCounterpartiesCounterpartyIdRoute:
    SlugDashboardCounterpartiesCounterpartyIdRoute,
  SlugDashboardDashboardsDashboardIdRoute:
    SlugDashboardDashboardsDashboardIdRoute,
  SlugDashboardInsightsInsightIdRoute: SlugDashboardInsightsInsightIdRoute,
  SlugDashboardInterestTemplatesInterestTemplateIdRoute:
    SlugDashboardInterestTemplatesInterestTemplateIdRoute,
  SlugDashboardTagsTagIdRoute: SlugDashboardTagsTagIdRoute,
  SlugDashboardTransactionsTransactionIdRoute:
    SlugDashboardTransactionsTransactionIdRoute,
  SlugDashboardAutomationsIndexRoute: SlugDashboardAutomationsIndexRoute,
  SlugDashboardBankAccountsIndexRoute: SlugDashboardBankAccountsIndexRoute,
  SlugDashboardBillsIndexRoute: SlugDashboardBillsIndexRoute,
  SlugDashboardBudgetsIndexRoute: SlugDashboardBudgetsIndexRoute,
  SlugDashboardCategoriesIndexRoute: SlugDashboardCategoriesIndexRoute,
  SlugDashboardCostCentersIndexRoute: SlugDashboardCostCentersIndexRoute,
  SlugDashboardCounterpartiesIndexRoute: SlugDashboardCounterpartiesIndexRoute,
  SlugDashboardDashboardsIndexRoute: SlugDashboardDashboardsIndexRoute,
  SlugDashboardGoalsIndexRoute: SlugDashboardGoalsIndexRoute,
  SlugDashboardInsightsIndexRoute: SlugDashboardInsightsIndexRoute,
  SlugDashboardInterestTemplatesIndexRoute:
    SlugDashboardInterestTemplatesIndexRoute,
  SlugDashboardTagsIndexRoute: SlugDashboardTagsIndexRoute,
  SlugDashboardTransactionsIndexRoute: SlugDashboardTransactionsIndexRoute,
}

const SlugDashboardRouteWithChildren = SlugDashboardRoute._addFileChildren(
  SlugDashboardRouteChildren,
)

interface SlugRouteChildren {
  SlugDashboardRoute: typeof SlugDashboardRouteWithChildren
  SlugExportRoute: typeof SlugExportRoute
  SlugImportRoute: typeof SlugImportRoute
  SlugOnboardingRoute: typeof SlugOnboardingRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugDashboardRoute: SlugDashboardRouteWithChildren,
  SlugExportRoute: SlugExportRoute,
  SlugImportRoute: SlugImportRoute,
  SlugOnboardingRoute: SlugOnboardingRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

interface AuthSignInRouteChildren {
  AuthSignInEmailRoute: typeof AuthSignInEmailRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthSignInRouteChildren: AuthSignInRouteChildren = {
  AuthSignInEmailRoute: AuthSignInEmailRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthSignInRouteWithChildren = AuthSignInRoute._addFileChildren(
  AuthSignInRouteChildren,
)

interface AuthRouteChildren {
  AuthAnonymousRoute: typeof AuthAnonymousRoute
  AuthEmailVerificationRoute: typeof AuthEmailVerificationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthSignInRoute: typeof AuthSignInRouteWithChildren
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnonymousRoute: AuthAnonymousRoute,
  AuthEmailVerificationRoute: AuthEmailVerificationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthSignInRoute: AuthSignInRouteWithChildren,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SlugRoute: SlugRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  FileHandlerRoute: FileHandlerRoute,
  PwaRedirectRoute: PwaRedirectRoute,
  ShareTargetRoute: ShareTargetRoute,
  CallbackOrganizationInvitationInvitationIdRoute:
    CallbackOrganizationInvitationInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
