export declare const env: Readonly<{
   VITE_POSTHOG_HOST: string;
   VITE_POSTHOG_KEY: string;
   DATABASE_URL: string;
   PG_VECTOR_URL?: string | undefined;
   REDIS_URL: string;
   BETTER_AUTH_SECRET: string;
   BETTER_AUTH_URL: string;
   BETTER_AUTH_TRUSTED_ORIGINS: string;
   BETTER_AUTH_GOOGLE_CLIENT_ID: string;
   BETTER_AUTH_GOOGLE_CLIENT_SECRET: string;
   STRIPE_SECRET_KEY: string;
   STRIPE_WEBHOOK_SECRET: string;
   STRIPE_BOOST_PRICE_ID?: string | undefined;
   STRIPE_SCALE_PRICE_ID?: string | undefined;
   STRIPE_ENTERPRISE_PRICE_ID?: string | undefined;
   POSTHOG_HOST: string;
   POSTHOG_KEY: string;
   POSTHOG_PUBLIC_KEY?: string | undefined;
   POSTHOG_PROJECT_ID: string;
   RESEND_API_KEY: string;
   MINIO_ENDPOINT: string;
   MINIO_ACCESS_KEY?: string | undefined;
   MINIO_SECRET_KEY?: string | undefined;
   MINIO_BUCKET: string;
   OPENROUTER_API_KEY?: string | undefined;
   TAVILY_API_KEYS?: string | undefined;
   EXA_API_KEYS?: string | undefined;
   FIRECRAWL_API_KEYS?: string | undefined;
   NODE_ENV: "development" | "production" | "test";
   APP_URL?: string | undefined;
   SERVER_URL?: string | undefined;
   SDK_SERVER_URL: string;
   LOG_LEVEL: "debug" | "error" | "fatal" | "info" | "trace" | "warn";
   WORKER_CONCURRENCY: number;
   DISCORD_FEEDBACK_WEBHOOK_URL?: string | undefined;
   GITHUB_FEEDBACK_TOKEN?: string | undefined;
   GITHUB_FEEDBACK_OWNER?: string | undefined;
   GITHUB_FEEDBACK_REPO?: string | undefined;
}>;
export type WebServerEnv = typeof env;
export type WebClientEnv = typeof env;
//# sourceMappingURL=web.d.ts.map
