name: Boundary

on:
   pull_request:
      branches: ["*"]
      types: [opened, synchronize, reopened, ready_for_review]

jobs:
   check:
      if: github.event.pull_request.draft == false
      runs-on: blacksmith-4vcpu-ubuntu-2404
      env:
         NX_SELF_HOSTED_REMOTE_CACHE_SERVER: ${{ secrets.NX_SELF_HOSTED_REMOTE_CACHE_SERVER }}
         NX_SELF_HOSTED_REMOTE_CACHE_ACCESS_TOKEN: ${{ secrets.NX_SELF_HOSTED_REMOTE_CACHE_ACCESS_TOKEN }}
      steps:
         - name: Checkout code
           uses: actions/checkout@v4
           with:
              fetch-depth: 0
              filter: tree:0

         - name: Bun & Nx Setup
           uses: ./.github/actions/setup-bun-nx

         - name: Run boundary check
           run: bun run check-boundaries
